//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpoloyeeDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class hgsIslem
    {
        public int hgsId { get; set; }
        public string müsteriNo { get; set; }
        public string Bakiye { get; set; }
    }
}
