//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HicFarketmezBank.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class host
    {
        public int hesapId { get; set; }
        public string hostadı { get; set; }
        public string hostdescription { get; set; }
        public string fiyat { get; set; }
        public string konum { get; set; }
        public string kullanıcıadı { get; set; }
        public string yorumlar { get; set; }
    }
}
