//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HicFarketmezBank.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kullanici
    {
        public int müsteriId { get; set; }
        public string isim { get; set; }
        public string soyisim { get; set; }
        public string kullanıcıadı { get; set; }
        public string parola { get; set; }
        public string telefon { get; set; }
    }
}
