//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HicFarketmezBank.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbBankAppEntities : DbContext
    {
        public dbBankAppEntities()
            : base("name=dbBankAppEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Havale> Havale { get; set; }
        public virtual DbSet<Hesap> Hesap { get; set; }
        public virtual DbSet<Müsteri> Müsteri { get; set; }
    }
}
